[[language]]
name = "java"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "nix"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "alejandra" }
auto-format = true

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "elixir"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
