{
  imports = [
    ./actual.nix
    ./circus.nix
    ./feishin.nix
    ./gonic.nix
    ./grafana.nix
    ./hydra.nix
    ./mcpo.nix
    ./netbird.nix
    ./newt.nix
    ./ntfy.nix
    ./odysseus.nix
    ./ollama.nix
    ./omni-tools.nix
    ./open-webui.nix
    ./syncthing.nix
    ./termix.nix
  ];
}
