name: Update flake lock

on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - run: nix flake update

      - uses: peter-evans/create-pull-request@v7
        with:
          title: Update flake lock
          body: "@ominit"
          commit-message: "update flake lock"
          branch: flake-update
          delete-branch: true
          base: main
          draft: false